name: SonarQube Scan (Local)

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full Git history for accurate analysis

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd forntend
          npm install

      - name: Run SonarQube Scan (Local)
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          args: >
            -Dsonar.projectKey=Full-Stack-Food-Delivery
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://abc123.ngrok.io


